// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using secretsantaapp.Database;

namespace secretsantaapp.Migrations
{
    [DbContext(typeof(SecretSantaContext))]
    [Migration("20220424130742_migracija4")]
    partial class migracija4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("secretsantaapp.Database.Gift", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime");

                    b.Property<int>("FromUsersId")
                        .HasColumnType("int");

                    b.Property<int>("ToUsersId")
                        .HasColumnType("int");

                    b.HasKey("GiftId");

                    b.HasIndex("FromUsersId");

                    b.HasIndex("ToUsersId");

                    b.ToTable("Gift");
                });

            modelBuilder.Entity("secretsantaapp.Database.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDuty")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("RolesId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            RoleDuty = "Upravljanje sistemom",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RolesId = 2,
                            RoleDuty = "Rad na sistemu",
                            RoleName = "Uposlenik"
                        });
                });

            modelBuilder.Entity("secretsantaapp.Database.Users", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UsersId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UsersId = 1,
                            Address = "Opine bb, Mostar",
                            Email = "belma@example.com",
                            FirstName = "Belma",
                            LastName = "Nukic",
                            PasswordHash = "yAOjokAWoWZ7AIriAcylq7elmVM=",
                            PaswordSalt = "X4BjiFAZ4rgva59Rabp8hg==",
                            Phone = "062147147",
                            Status = false,
                            Username = "belma"
                        },
                        new
                        {
                            UsersId = 2,
                            Address = "Jukiceva 36, Sarajevo",
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = "ohXrySDeRILoN47ntKghKMuytn0=",
                            PaswordSalt = "HJbj66wjuAzLNxDYlZ/T9A==",
                            Phone = "063222111",
                            Status = false,
                            Username = "admin"
                        },
                        new
                        {
                            UsersId = 3,
                            Address = "Sehovina bb, Mostar",
                            Email = "uposlenik@gmail.com",
                            FirstName = "Uposlenik",
                            LastName = "Uposlenik",
                            PasswordHash = "fhbMFkIaC3MAqqVJ3Pv5v+oJrr8=",
                            PaswordSalt = "MUbkLKLde+Ym9kT9RJuaBw==",
                            Phone = "063132233",
                            Status = false,
                            Username = "uposlenik"
                        },
                        new
                        {
                            UsersId = 4,
                            Address = "Opine bb, Mostar",
                            Email = "ema@gmail.com",
                            FirstName = "Ema",
                            LastName = "Bojcic",
                            PasswordHash = "ySI1sfGjOEtRDU6tOzFMnyO0afM=",
                            PaswordSalt = "BRl3JcN1K/rTRcjwEm4Z3Q==",
                            Phone = "0631231323",
                            Status = false,
                            Username = "ema"
                        });
                });

            modelBuilder.Entity("secretsantaapp.Database.UsersRoles", b =>
                {
                    b.Property<int>("UsersRolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UsersRolesId");

                    b.HasIndex("RolesId");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersRoles");

                    b.HasData(
                        new
                        {
                            UsersRolesId = 1,
                            PublishedDate = new DateTime(2022, 4, 24, 15, 7, 40, 807, DateTimeKind.Local).AddTicks(1615),
                            RolesId = 1,
                            UsersId = 2
                        },
                        new
                        {
                            UsersRolesId = 2,
                            PublishedDate = new DateTime(2022, 4, 24, 15, 7, 40, 822, DateTimeKind.Local).AddTicks(7887),
                            RolesId = 2,
                            UsersId = 1
                        },
                        new
                        {
                            UsersRolesId = 3,
                            PublishedDate = new DateTime(2022, 4, 24, 15, 7, 40, 822, DateTimeKind.Local).AddTicks(8289),
                            RolesId = 2,
                            UsersId = 3
                        },
                        new
                        {
                            UsersRolesId = 4,
                            PublishedDate = new DateTime(2022, 4, 24, 15, 7, 40, 822, DateTimeKind.Local).AddTicks(8364),
                            RolesId = 2,
                            UsersId = 4
                        });
                });

            modelBuilder.Entity("secretsantaapp.Database.Gift", b =>
                {
                    b.HasOne("secretsantaapp.Database.Users", "FromUsers")
                        .WithMany("GiftFromUsers")
                        .HasForeignKey("FromUsersId")
                        .HasConstraintName("fk_fromusers")
                        .IsRequired();

                    b.HasOne("secretsantaapp.Database.Users", "ToUsers")
                        .WithMany("GiftToUsers")
                        .HasForeignKey("ToUsersId")
                        .HasConstraintName("fk_tousers")
                        .IsRequired();
                });

            modelBuilder.Entity("secretsantaapp.Database.UsersRoles", b =>
                {
                    b.HasOne("secretsantaapp.Database.Roles", "Roles")
                        .WithMany("UsersRoles")
                        .HasForeignKey("RolesId")
                        .HasConstraintName("fk_roleid")
                        .IsRequired();

                    b.HasOne("secretsantaapp.Database.Users", "Users")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UsersId")
                        .HasConstraintName("fk_usersid")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
